export const landingHeroDefaults = {
  badge: "Grand academy experience for Bangladesh",
  badge_bn: "বাংলাদেশের জন্য গ্র্যান্ড একাডেমি এক্সপেরিয়েন্স",
  title_prefix: "This is",
  title_prefix_bn: "এটাই হলো",
  title_highlight: "Shaharia Math",
  title_highlight_bn: "শাহরিয়া ম্যাথ",
  title_suffix: "rebuilt to feel premium, modern, and unmistakably powerful.",
  title_suffix_bn: "— প্রিমিয়াম, আধুনিক এবং শক্তিশালী।",
  description:
    "For BBA, MBA, Mathematics, Accounting, Management, Finance, Marketing, Job Preparation, SSC, and HSC — smooth phone OTP entry, polished student flow, and a premium academy identity with Shaharia Math.",
  description_bn:
    "BBA, MBA, Mathematics, Accounting, Management, Finance, Marketing, SSC, HSC — ফোন OTP দিয়ে স্মুথ এন্ট্রি, পালিশড স্টুডেন্ট ফ্লো এবং শাহরিয়া ম্যাথের সাথে প্রিমিয়াম একাডেমি।",
  primary_cta: "Enroll with Phone OTP",
  primary_cta_bn: "ফোন OTP দিয়ে ভর্তি হন",
  primary_cta_url: "/join",
  secondary_cta: "Watch Free Classes",
  secondary_cta_bn: "ফ্রি ক্লাস দেখুন",
  secondary_cta_url: "/free-classes",
  bullet_1: "Bangla-first experience",
  bullet_1_bn: "বাংলা-ফার্স্ট এক্সপেরিয়েন্স",
  bullet_2: "Live + recorded support",
  bullet_2_bn: "লাইভ + রেকর্ডেড সাপোর্ট",
  bullet_3: "Premium academy",
  bullet_3_bn: "প্রিমিয়াম একাডেমি",
  image_url: "",
  dashboard_eyebrow: "Academy dashboard",
  dashboard_eyebrow_bn: "একাডেমি ড্যাশবোর্ড",
  dashboard_text: "Built for focus, trust, and fast action",
  dashboard_text_bn: "ফোকাস, আস্থা ও দ্রুত ব্যবহারের জন্য",
  journey_eyebrow: "Student journey",
  journey_eyebrow_bn: "স্টুডেন্ট জার্নি",
  journey_title: "One academy. One clean flow.",
  journey_title_bn: "এক একাডেমি। পরিষ্কার ফ্লো।",
  live_label: "Live",
  live_label_bn: "লাইভ",
  step_1: "Enter your number and verify with OTP",
  step_1_bn: "নম্বর দিন এবং OTP দিয়ে ভেরিফাই করুন",
  step_2: "Pick the right department and program",
  step_2_bn: "সঠিক বিভাগ ও প্রোগ্রাম বেছে নিন",
  step_3: "Join classes, groups, and study flow",
  step_3_bn: "ক্লাস, গ্রুপ এবং স্টাডি ফ্লোতে যোগ দিন",
  access_label: "Access",
  access_label_bn: "অ্যাক্সেস",
  access_text: "OTP-first login",
  access_text_bn: "OTP-ফার্স্ট লগইন",
  brand_label: "Brand strength",
  brand_label_bn: "ব্র্যান্ড স্ট্রেংথ",
  brand_text: "A bolder academy identity — credible, premium, and ready to scale.",
  brand_text_bn: "আরও সাহসী একাডেমি — বিশ্বাসযোগ্য ও স্কেলের জন্য প্রস্তুত।",
  stat_1_value: "10,000+",
  stat_1_label: "Students mentored",
  stat_1_value_bn: "১০,০০০+",
  stat_1_label_bn: "শিক্ষার্থী গাইডেড",
  stat_2_value: "500+",
  stat_2_label: "Live classes delivered",
  stat_2_value_bn: "৫০০+",
  stat_2_label_bn: "লাইভ ক্লাস সম্পন্ন",
  stat_3_value: "9",
  stat_3_label: "Academic tracks",
  stat_3_value_bn: "৯",
  stat_3_label_bn: "একাডেমিক ট্র্যাক",
  stat_4_value: "OTP",
  stat_4_label: "Fast phone login",
  stat_4_value_bn: "OTP",
  stat_4_label_bn: "দ্রুত ফোন লগইন",
};

export type LandingHeroContent = typeof landingHeroDefaults;
